"""initial migration

Revision ID: d5d21dc431b0
Revises: 
Create Date: 2023-01-19 14:57:30.707660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5d21dc431b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('UNIQ_8D93D649E7927C74')

    op.drop_table('user')
    with op.batch_alter_table('messenger_messages', schema=None) as batch_op:
        batch_op.drop_index('IDX_75EA56E016BA31DB')
        batch_op.drop_index('IDX_75EA56E0E3BD61CE')
        batch_op.drop_index('IDX_75EA56E0FB7336F0')

    op.drop_table('messenger_messages')
    op.drop_table('doctrine_migration_versions')
    op.drop_table('future_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('future_user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('nationality', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('is_validated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('doctrine_migration_versions',
    sa.Column('version', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=191), nullable=False),
    sa.Column('executed_at', mysql.DATETIME(), nullable=True),
    sa.Column('execution_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('version'),
    mysql_collate='utf8mb3_unicode_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('messenger_messages',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('body', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('headers', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('queue_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=190), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('available_at', mysql.DATETIME(), nullable=False),
    sa.Column('delivered_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('messenger_messages', schema=None) as batch_op:
        batch_op.create_index('IDX_75EA56E0FB7336F0', ['queue_name'], unique=False)
        batch_op.create_index('IDX_75EA56E0E3BD61CE', ['available_at'], unique=False)
        batch_op.create_index('IDX_75EA56E016BA31DB', ['delivered_at'], unique=False)

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=180), nullable=False),
    sa.Column('roles', mysql.JSON(), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('nationality', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('UNIQ_8D93D649E7927C74', ['email'], unique=False)

    op.drop_table('car_model')
    # ### end Alembic commands ###
